# -*- coding: utf-8 -*-
"""Semana1PythonBasic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10VCbEGA7l2TOhkvxk5KAs5CkawsnUL0o

DECLARAR VARIABLES:
"""

i = 10
f = 3.7
s = "Ernesto"

print("Integer = ",i)
print("Flotante = ",f)
print("String = ",s)

"""Ciclo Repetitivo"""

for i in range(1, 7):
  print("Linea ", i)

"""Lista"""

lista = []
for i in range(10):
  lista.append(i)
print(lista)

"""Funcion"""

def function(n):
  return 2*n

print("Resultado de la funcion: ", function(7))

lineal
lineal
cuadratica